FROM node:16

# Create app directory
RUN mkdir -p /app
WORKDIR /app

# Install app dependencies
COPY ./package.json /app
COPY ./yarn.lock /app
COPY ./.yarnrc.yml /app
RUN yarn install

# Bundle app source
COPY . /app
RUN yarn build
#RUN yarn test